### ISSUE TITLE
Document Grid System and other features added in theme

### ISSUE THREAD

**Issue by wesruv** [backdrop-contrib/basis#11]
See @Graham-72's questions #4.

**Comment by klonos** [comment]
...using really short versions of words in the classes (like l-col-**lg**-6 for example) does not help. If we used the full-length equivalent it might make things a bit more self-explanatory. I realize that this would mean a DX- because people would have to type longer classes, but _Backdrop values site builders over coders._ (https://backdropcms.org/philosophy).

**Comment by klonos** [comment]
...plus, that `l` in the class might be confused for a capital `i` by people which could lead to a whole lot of issues.

**Comment by Graham-72** [comment]
Adding this link here or I will never find this excellent exposition again :grin: 
https://github.com/backdrop/backdrop-issues/issues/698#issuecomment-213136964

**Comment by wesruv** [comment]
@klonos good point. I generally loathe abbreviation, because it raises things like "what should I abbrev, and what should I not" and tends to add inconsistency.

The `l-` is from current backdrop core, and the `lg` is a bootstrap hold-over. 

I'm certainly glad to do a quick find and replace to change all of the breakpoint names to abbreviated versions, but I'm a little hesitant to change `l-` to `layout-`... anyone else have thoughts on this?

CC'ing some people that might be interested that might not see this otherwise:
@quicksketch @jenlampton @mikemccaffrey @docwilmot

**Comment by Graham-72** [comment]
Initially when working with Backdrop I found the l- abbreviation difficult because of confusion with 1 or I depending on typeface, but I have got used to it. Surely we could do better?

**Comment by jenlampton** [comment]
`l-` is a standard we adopted from the internet at large. I personally don't have a problem with l- at the beginning (indicating CSS for these files will be in the layouts only) and -lg -md -sm and -xs (or -vs) indicating breakpoints. I'd rather stick to standards that people from outside backdrop will recognize than reinvent the wheel for ourselves.

> that l in the class might be confused for a capital i by people

All our CSS classes are lower case. I doubt this confusion will happen often. In general everyone has been really happy with the 'l-' prefixes.  Let's leave them alone, as there's a cost that comes with change!

> Backdrop values site builders over coders.

This is meant to mean that the User Interfaces are more important. Once people make the jump from User Interface to code, we do expect they will be savvy enough to figure things out - people are smart! And the more common standards we use, the more likely they will have seen some of it elsewhere before.

I would like to add that perhaps we should not be adding `l-` to the bootstrap grid column classes. Every layout region should have one class on it with `l-`(something like `l-left` or `l-first`) but I don't think we should be changing the names of the bootstrap classes. That sort-of defeats the purpose of using something that's standard.

**Comment by jenlampton** [comment]
Also - and maybe a more important note for this issue - there should not be a grid system included in any theme ;)  @wesruv maybe you meant "layout module" or "system module" or ??  Or maybe this is just "Document it before it gets moved to wherever it will eventually be..."  Also valid! :)

**Comment by wesruv** [comment]
@jenlampton yes! Definitely going to move this to the layout module, it's only in basis right now because of my laziness, and because I'm developing it as a contrib theme right now.

**Comment by jenlampton** [comment]
makes sense :)

**Comment by klonos** [comment]
All of this sounds fair enough and to be honest, I kinda expected replies like these. I merely wanted to bring these points up and see what others think because a) I was thinking that we could perhaps lower the entry point by making things as self-explanatory as possible and b) this is a documentation issue that would be a non-issue if the class names were not abbreviated (and hence cryptic to most).

As I said, fair enough. I don't feel strong about abbreviating classes or not. Either way is fine by me. Especially if the abbreviated versions of things we use is a generally accepted/established standard.

Thanx everybody for taking the time to chime in.

**Comment by jenlampton** [comment]
@klonos ++

**Comment by klonos** [comment]
...BTW (<-- abbreviation), my silly self intended to make a comment on @wesruv's comment, but forgot (emphasis mine):

> **I generally loathe abbreviation**, because it raises things like "**what should I abbrev**, and what should I not" and tends to add inconsistency.

LOL

**Comment by jenlampton** [comment]
"what should I **abbrev** and how much should we **abrv** it?"

**Comment by klonos** [comment]
:laughing:

**Comment by wesruv** [comment]
@klonos @Graham-72 ... and whoever else :stuck_out_tongue: 

Can you check out the CSS docs I've added and let me know how I did?
https://github.com/backdrop-contrib/basis/tree/master/css
https://github.com/backdrop-contrib/basis/tree/master/css/grid-system

Thinking I'll add some images/examples in the long run, but I **think** this is all the major stuff to document in README's. Let me know if there's anything else you'd care to see documented.

**Comment by jenlampton** [comment]
This looks pretty good!!! :)

> l- prefix of all layout classes

For the core css, we should remove this difference from bootstrap so that people who are familiar with it already don't have to change their ways for Backdrop :)

**Comment by Graham-72** [comment]
@wesruv thanks for this. One problem, on my small site I have one page that uses the single column layout and the header-name-and-slogan div is appearing somewhere towards the centre, not where it is in the 2 column layout.
![photo gallery - kyson fairways 2016-04-25 07-42-15](https://cloud.githubusercontent.com/assets/10559274/14775773/5eb2534a-0ab9-11e6-95fb-1d91a3181b5c.png)

**Comment by wesruv** [comment]
@Graham-72 ahh, I can push a fix for that. That style is intended for mobile sizes and didn't effect my default layout at desktop sizes.

@jenlampton I'd like to make the CSS architecture in a way that's it's easy to spot CSS functional selectors that should not be extended.

E.g. no one should be writing classes like these:

```
.l-main .col-md-9 { ... }
.l-sidebar .clearfix { ... }
```

I think asking people to avoid magic class names is less clear than saying 'avoid classes that start with these prefixes', although `l-` doesn't work well in that instance.

Maybe `l-` isn't the right prefix, but I think these should be name-spaced. I think it'll make it a lot easier to pick up on, and at the low price of telling people used to bootstrap that we prefix the classes they're used to.

I've been wanting to prefix all of our utility classes (e.g. clearfix, element-invisible) with `u-`.

**Comment by Graham-72** [comment]
> That style is intended for mobile sizes

I'm a bit puzzled by this and what you mean by style here. I want to be able to use a single column layout interchangeably with a two-column layout (and possibly others) in the same site and for all screen sizes. Am I expecting too much? I am probably misunderstanding you.
But thanks (in anticipation) for the fix.

**Comment by wesruv** [comment]
@Graham-72 I _think_ I just pushed a fix to that issue. I couldn't replicate the issue on the current version of your site, not sure if you reverted or updated the theme?

Here's the commit:
https://github.com/backdrop-contrib/basis/commit/50ed94b7d552406f2092c0fabaca9b4ded039473

**Comment by Graham-72** [comment]
@wesruv I have just used your commit to update my site, and as I have commented on that commit, things are really good. Many thanks.

**Comment by wesruv** [comment]
Closing this since the docs are going to be in the layout module and looks like biolithic is going to knock it out :smile:
