### ISSUE TITLE
Site slogan color needs attention.

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/basis#19]
'Out of the box' the site slogan would seem to be colored black and hardly shows on the near-black header background.

**Comment by klonos** [comment]
Perhaps a screenshot would help:

![backdrop-contrib-basis-issue19](https://cloud.githubusercontent.com/assets/2423362/17851491/99fbdf12-68a5-11e6-8b8b-d5f633607dfa.png)

**Comment by klonos** [comment]
Trivial change. Please check my PR.

**Comment by wesruv** [comment]
Fixed: https://github.com/backdrop-contrib/basis/commit/e7382d0c5f6d4cbda85da8de87ef3ba225afc8b6#diff-f96cf367b7993500e4f794c7bbdaab91L204

**Comment by klonos** [comment]
👍 I don't really care that much about the implementation - all I know is that it's fixed! Thanx 👍
