### ISSUE TITLE
Make Open Sans font use relative paths

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/basis#20]
With my site installed in a subdirectory backdrop, the links to the fonts are still referring to my domain name and not including the /backdrop, whereas this is being added for other links in the site.

**Comment by wesruv** [comment]
Eek! That should be an easy fix.

**Comment by wesruv** [comment]
Pushed a fix to the 1.0.x branch:
https://github.com/backdrop-contrib/basis/commit/6e2a23c13705c905d298da8ddb814bacfe850548

I'm going to close this, but let me know if there are still issues.
