### ISSUE TITLE
How to center the main menu?

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/basis#21]
@wesruv I am using Basis on another site and would like to center the main menu horizontally. I have managed to center the site name and slogan, but cannot find the right CSS to use to center the main menu. Here is a preview of where I am at (it's early days!)
![welcome catherine larner](https://cloud.githubusercontent.com/assets/10559274/15590280/c68bd746-238e-11e6-8ac8-8562478475dc.png)

**Comment by Graham-72** [comment]
I have found the answer. It was line 247 in layout.css ' justify-content: flex-start; ' that needed a change to be justify-content: center;

**Comment by wesruv** [comment]
Yep! You got it, sorry I didn't back to you in a timely manner.

This is where I learned all the flex box things, really well crafted explanation:
https://css-tricks.com/snippets/css/a-guide-to-flexbox/

**Comment by Graham-72** [comment]
@wesruv No problem, I know how busy you have been! Thanks for the link.
