### ISSUE TITLE
Header site name font weight.

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/basis#25]
In header.tpl.php we have
`
 <div class="header-name-and-slogan-wrapper">

```
    <?php if (!$is_front): ?>

      <div class="header-site-name-wrapper">

        <strong>

          <a href="<?php print $front_page; ?>" title="<?php print t('Home'); ?>" class="header-site-name-link" rel="home">

            <?php print $site_name; ?>

          </a>

        </strong>

      </div>
```

`

This gives an unexpected result when using a page as the front page because the presence of 'strong' in the template applies on pages other than the front page and not on the front page..

I would prefer the template not to specify the font weight i.e. please remove the strong.

**Comment by klonos** [comment]
Yep. Unless there is a very good reason, we should have font weight defined in CSS (using `body .front` if you want it applied _only_ on the front page).

**Comment by wesruv** [comment]
@Graham-72 I'm pretty sure I'm not the one that added that, but `<strong>` has a semantic meaning. I assume the preference wasn't to use a heading tag (which would also default to bold) as that implies it's part of the document outline. 

That is a common practice (that's what I usually do), and headings also default to bold like the `<strong>` tag does.

In the short term, I'd define font-weight on the `.header-site-name-link` class, or you could remove the strong tag in your sub theme.

I'll do some research, my gut is that `<strong>` isn't a good choice, but what it gets replaced with might also default to bold.

**Comment by Graham-72** [comment]
My problem is not that it appears bold but that it is different on the front page. Other pages do not seem to have `<strong>` so yes, I have to remove it from the front page in my sub theme.

**Comment by wesruv** [comment]
I _think_ the reason they may have done that is to give it more semantic juice on the homepage. Kind of a weird choice, IMO.

**Comment by wesruv** [comment]
After doing research, I think `<strong>` is a good choice, but there's no reason to limit that to the homepage. With the coming of the HTML5 document outline which will provide importance to the outermost `<header>` tag, I don't think `<h1>` is a good choice anymore.

To address @Graham-72 styling concerns we can add a style that sets `font-weight: inherit`, so the `<strong>` tag will only provide semantic influence but not the style.

In the end, the 'SEO-ness' has no right answer. From a semantic and screen-reader perspective, I think `<header>` and `<strong>` are the most appropriate, unless someone knows something I don't.

I'm going to put a PR together, @Graham-72 would you be able to test it to see if solves the issues you were having?

**Comment by Graham-72** [comment]
> so the tag will only provide semantic influence but not the style.

That sounds fine thank you.

> would you be able to test it to see if solves the issues you were having?

Yes certainly, I will gladly test it.

**Comment by klonos** [comment]
I will give it a spin too if I manage to make some time. Just let us know when you're ready @wesruv

**Comment by wesruv** [comment]
@Graham-72 and @klonos 
If you have the time give this a shot, let me know what you think: 
https://github.com/backdrop-contrib/basis/pull/32

**Comment by klonos** [comment]
> If you have the time...

😆 😆 ...good one!! 😆 

I'll try to make some time throughout the weekend.

**Comment by Graham-72** [comment]
> If you have the time give this a shot, let me know what you think

:+1: I have now tested this and it does the job, thank you - a big improvement.
I have tried in various browsers and the only problem I have is with my Android tablet - issue #22.

**Comment by wesruv** [comment]
Awesome, merged!
