### ISSUE TITLE
Provide additional help for setting banner and page title classes.

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/basis#26]
For either nodes or views as pages there is a problem if you want to apply classes for specific pages because the node id or the view name are rendered after the header and page title.

One need I had was where I wanted different banner images for different pages. Another need I have had is where I needed extra margin in a particular view and wanted the page title to have the same left margin as the content provided by the view.

My solution has been to add this capability with a preprocess page function in my theme template.php, like this
![hook_preprocess_page](https://cloud.githubusercontent.com/assets/10559274/16709918/163fc884-4616-11e6-824d-81673a1ca79a.png)

Perhaps there are other ways of doing it? Why not include this or similar in the theme?

**Comment by wesruv** [comment]
Man, I haven't been getting emails for new issues, sorry for the delay!

That's a fine way of doing that, I can see the benefit of doing something like this and having it in the theme. I'll get it added!

**Comment by wesruv** [comment]
Feel free to submit a PR as well!

**Comment by wesruv** [comment]
Merged, thanks so much @Graham-72 !
