### ISSUE TITLE
Impossible to install it

### ISSUE THREAD

**Issue by bd0bd** [backdrop-contrib/basis#29]
Impossible to install it from here:

```
/admin/installer/manual
```

Only manual via FTP.

**Comment by wesruv** [comment]
There's an issue with the script that pulls in new modules and themes, after that's fixed this _should_ show up.

**Comment by wesruv** [comment]
Got it! Found out I needed to add release notes to make the release function properly.

Thanks for calling my attention to this!
https://backdropcms.org/project/basis
