### ISSUE TITLE
No any settings

### ISSUE THREAD

**Issue by bd0bd** [backdrop-contrib/basis#30]
There are no any settings here: /admin/appearance/settings/basis

Only SAVE THEME SETTINGS button is visible.

**Comment by wesruv** [comment]
I'll get this removed if I'm not able to add settings before long. The intention is to have some really cool settings :stuck_out_tongue:

**Comment by bd0bd** [comment]
Thank you! I see. Of cause it would be cool to have cooler settings :smile:

**Comment by wesruv** [comment]
Not sure I'll be getting to cool settings before we get this in core :disappointed: 
Removed settings flags for now. 81eb38156150d2c1eb849b63a3484dacfbfef044

**Comment by klonos** [comment]
No worries @wesruv, we have #1 as a to-do for that 😉
