### ISSUE TITLE
Improve hover styles for paging.

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/basis#31]
The style of the paging control looks smart except when hovering over 'first' or 'previous' when it looks a bit untidy.
![basispaginghover](https://cloud.githubusercontent.com/assets/10559274/17012026/9662abdc-4f0b-11e6-9fb3-39705452fbb3.png)

**Comment by wesruv** [comment]
Could only replicate this in firefox, but got it fixed methinks.
356196f

**Comment by wesruv** [comment]
Reopen if there are still issues

**Comment by Graham-72** [comment]
:+1:  :+1:
