### ISSUE TITLE
Read more and Add comment link positioned oddly

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/basis#45]
The link for "Read more" looks nice in its pseudo-button form (IMO), but its neighbors like "Add comment" are oddly placed in respect to it. Maybe put them side-by-side instead?

![selection_172](https://cloud.githubusercontent.com/assets/100206/18074660/12013f5c-6e23-11e6-942e-979d93a87ede.png)

**Comment by serundeputy** [comment]
I took a shot at this.  I'm up for criticism.

![screen shot 2016-08-30 at 7 42 36 pm](https://cloud.githubusercontent.com/assets/6763671/18111001/080d3222-6eea-11e6-8553-39223e7f051a.png)

**Comment by klonos** [comment]
Looks better to me now, but merely because I like consistency and having one link and one button for similar actions triggers my OCD. Although, I have to say that anything that is a link, I expect it to take me to a different page. With buttons I expect pop-up dialogs/modals to happen. Just my 2c.

**Comment by wesruv** [comment]
I was a little torn on this one. The tricky part is the comments may have multiple links:
![image](https://cloud.githubusercontent.com/assets/5607236/18180671/edfbfb76-7055-11e6-9007-39bb5d530bf9.png)

I was trying to create hierarchy, and I figure the point of a teaser is to get the user to go to the full page. So I wanted to have Read more be a little more prominent, and it felt like it something that could share the button styles.

**Comment by wesruv** [comment]
Looks like this one's been fixed
