### ISSUE TITLE
Make header less opinionated and more flexible for customization

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/basis#49]
I have been having diificulty in customising the header layout and adding classes in a subtheme to modify the layout produced by flexbox styles.

In particular, I want to be able to add a custom block at the top right of a page when on a wide screen, hopefully by using justify-content: space-around to get my added block into position.

But I was having difficulty applying styles to the relevant divs and the root of the problem would seem partly to be the use of the selector  ' .l-header .block > div ' in layout.css, which applies to the line 
div class="block-content" in the block.tpl.php code. See below
![basis_block_code](https://cloud.githubusercontent.com/assets/10559274/18166780/fc10b122-7044-11e6-95f5-4a7e83d168cc.png)

Would a solution be to add more classes to this div so that the identity of the block is included here and a custom style can then be applied to the contents of the block? I am trying the use of 
`
<div class="block-content <?php print implode(' ', $classes); ?>">
`
in the block template and this does what I need but may have unwanted side effects. Any other suggestions please?

**Comment by wesruv** [comment]
Blurg, I'm sorry about this! That style is crap, I was thinking about solving a specific issue when I wrote it, but didn't think about the consequences very well.

I would recommend overriding my CSS file that's making these header styles and removing this one in particular. I'm going to go back to the drawing board on the design for the header and do something that doesn't require as much opinionated CSS.

That should remove the need for duplicating the classes on the block-content div.

**Comment by wesruv** [comment]
Here's an idea for the design: https://github.com/backdrop/backdrop-issues/issues/1361#issuecomment-244248246

**Comment by wesruv** [comment]
Updated issue title so I'll remember what this is :D

**Comment by Graham-72** [comment]
@wesruv thanks for responding and I like your change of title for this issue. Basis is going to be great!

Just now I am puzzled as to where in the templates the block-content div is being produced. In one case on my site (under development) it is being produced as class = "" which is even more unhelpful.

**Comment by wesruv** [comment]
@Graham-72 RE: finding where that's being produced, it's probably in core? To debug, I would enable theme_debug by:
- Go to config directory
- Open active directory
- Find `system.core.json`
- Find `theme_debug` key and change it to `1`

That will produce HTML comments around tpl files that will tell you where that markup is being generated, like these ones:
![image](https://cloud.githubusercontent.com/assets/5607236/18413923/02c07438-7786-11e6-9966-60fa551d238d.png)

**Comment by wesruv** [comment]
Per this issue I've _mostly_ finished the simplified header, but the styles for small screens still need some love. Need to think on it, I'll finish it up tomorrow.

@Graham-72 if you get a chance, try the updates on from the latest commits on `1.x-0.x` and let me know what you think. It might break some of your old styles because there's no more flex box being used anywhere in the header, but should be a lot easier to work with.

I also noticed I hadn't created a separate file for the header for easy overriding. Added `l-header.css` in `components` folder.

**Comment by wesruv** [comment]
I would also like to note that there is a 37% reduction in lines of CSS to make the header, #w00t

**Comment by Graham-72** [comment]
@wesruv thanks, I will give it a try today (UK time).

**Comment by wesruv** [comment]
Updated it again, I think I got everything I wanted in there.

**Comment by Graham-72** [comment]
@wesruv what are your thoughts on locating custom styles? I have started trying out your new header and was adding custom styles at the end of l-header.css, and then wanted to change the whole background color for the header, but this is in skin.css which is declared after l-header.css in basis.info.

Would it not be better perhaps to provide an empty custom.css and list this after the other css files in basis.info? Then I could add my custom styles knowing they would over-ride the out-of-the-box styles. Or some similar arrangement.

**Comment by Graham-72** [comment]
>  let me know what you think

I'm very pleased with what is now possible, thank you. 
I think I also need to over-ride the min-width values for .container in core/modules/layout/css/grid-flexbox.css.

**Comment by Graham-72** [comment]
Ah! I have now seen your README.md in the css folder. I hadn't thought to look for one there - in too much of a rush to try Basis!

**Comment by wesruv** [comment]
Ha! Sorry it took me a bit to get back to you, does the recommended way from the README work in practice?

I figure "most people" want to override colors and add a few things. I think overriding skin is the best place to start and then override component CSS as needed. That way a lot of structure can be inherited and you won't have to think about it as much.

If you want to get into both the skin and a lot of the component structure I think it'll be a little annoying with the colors being in skin (only) and everything else being in component files.

If you prefer to work on top of what's there, I believe adding a `custom.css` to your sub-theme's info will put it after everything in `basis` which should get you what you were originally expecting.

Thanks so much for the feedback @Graham-72, you're comments & questions were incredibly helpful for me!
