### ISSUE TITLE
Navigation opening tag could be more helpful

### ISSUE THREAD

**Issue by illfittingshoes** [backdrop-contrib/basis#52]
A couple small thoughts...

Should `div[role=navigation]` be a `<nav>`?

The nav item for the current page has an 'active' class. Since 'active' is a CSS pseudo-class, perhaps something like "current" or "active-page" would be clearer?

**Comment by wesruv** [comment]
Posted these to an issue in core, both great points, danke!
https://github.com/backdrop/backdrop-issues/issues/2175
