### ISSUE TITLE
no-flexbox overridees in layout.css are inconsistently placed

### ISSUE THREAD

**Issue by illfittingshoes** [backdrop-contrib/basis#54]
- `.gallery` is inline
  - perhaps overly inline, as there are more styles on the same selector after the override that don't seem to need to be separated
- All others (`l-header...` and `header-name-and-slogan-wrapper`) are all together at the bottom

**Comment by wesruv** [comment]
These ended up getting changed, but that's good feedback, I'll keep a better eye out in the future.

Only place they're in now is `pager.css` and I updated it to go immediately after the flexbox styles.
